import React, { useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, Share } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import Colors from '../../assets/constants/colors';
import { AnalyticsData } from '../../services/Premium/AnalyticsService';

const colors = Colors.dark;

interface FocusReportProps {
  analytics: AnalyticsData;
  timeframe: 'week' | 'month' | 'year';
  onExport: (format: 'json' | 'csv') => void;
}

const FocusReport: React.FC<FocusReportProps> = ({
  analytics,
  timeframe,
  onExport
}) => {
  const [expandedSection, setExpandedSection] = useState<string | null>(null);

  const getTimeframeLabel = () => {
    switch (timeframe) {
      case 'week': return 'This Week';
      case 'month': return 'This Month';
      case 'year': return 'This Year';
      default: return 'This Period';
    }
  };

  const getProgressData = () => {
    const currentData = analytics.weeklyProgress.slice(-7);
    const previousData = analytics.weeklyProgress.slice(-14, -7);
    
    const currentTotal = currentData.reduce((sum, week) => sum + week.completedSessions, 0);
    const previousTotal = previousData.reduce((sum, week) => sum + week.completedSessions, 0);
    
    const currentFocusTime = currentData.reduce((sum, week) => sum + week.totalFocusTime, 0);
    const previousFocusTime = previousData.reduce((sum, week) => sum + week.totalFocusTime, 0);
    
    const currentSuccess = currentData.reduce((sum, week) => sum + week.successRate, 0) / currentData.length;
    const previousSuccess = previousData.reduce((sum, week) => sum + week.successRate, 0) / previousData.length;
    
    return {
      sessions: {
        current: currentTotal,
        previous: previousTotal,
        change: previousTotal > 0 ? ((currentTotal - previousTotal) / previousTotal) * 100 : 0
      },
      focusTime: {
        current: currentFocusTime,
        previous: previousFocusTime,
        change: previousFocusTime > 0 ? ((currentFocusTime - previousFocusTime) / previousFocusTime) * 100 : 0
      },
      successRate: {
        current: currentSuccess,
        previous: previousSuccess,
        change: previousSuccess > 0 ? currentSuccess - previousSuccess : 0
      }
    };
  };

  const progressData = getProgressData();

  const generateInsights = () => {
    const insights = [];
    
    if (progressData.sessions.change > 10) {
      insights.push({
        type: 'positive',
        icon: 'trending-up',
        title: 'Great Progress!',
        description: `You've improved your session count by ${Math.round(progressData.sessions.change)}% compared to last period.`
      });
    }
    
    if (progressData.focusTime.change > 15) {
      insights.push({
        type: 'positive',
        icon: 'time',
        title: 'Increased Focus Time',
        description: `You're spending ${Math.round(progressData.focusTime.change)}% more time in focused sessions.`
      });
    }
    
    if (progressData.successRate.current < 60) {
      insights.push({
        type: 'improvement',
        icon: 'warning',
        title: 'Room for Improvement',
        description: 'Consider using Timer Lock Mode to improve your completion rate.'
      });
    }
    
    if (analytics.currentStreak > 7) {
      insights.push({
        type: 'achievement',
        icon: 'flame',
        title: 'Streak Master!',
        description: `Amazing! You've maintained a ${analytics.currentStreak}-day focus streak.`
      });
    }
    
    return insights;
  };

  const insights = generateInsights();

  const exportReport = async () => {
    try {
      const reportData = {
        timeframe: getTimeframeLabel(),
        summary: {
          totalSessions: analytics.sessionsCompleted,
          totalFocusTime: Math.round(analytics.totalFocusTime / 60000),
          averageSessionDuration: Math.round(analytics.averageSessionDuration / 60000),
          currentStreak: analytics.currentStreak,
          successRate: Math.round((analytics.sessionsCompleted / (analytics.sessionsCompleted + analytics.sessionsCancelled)) * 100)
        },
        progress: progressData,
        insights: insights,
        recommendations: analytics.improvementSuggestions
      };
      
      const message = `Focus Report - ${getTimeframeLabel()}\n\n` +
        `Total Sessions: ${reportData.summary.totalSessions}\n` +
        `Focus Time: ${reportData.summary.totalFocusTime} minutes\n` +
        `Avg Session: ${reportData.summary.averageSessionDuration} minutes\n` +
        `Current Streak: ${reportData.summary.currentStreak} days\n` +
        `Success Rate: ${reportData.summary.successRate}%\n\n` +
        `Generated by OffScreen Buddy Pro`;
      
      await Share.share({ message });
    } catch (error) {
      console.error('Failed to export report:', error);
    }
  };

  const toggleSection = (section: string) => {
    setExpandedSection(expandedSection === section ? null : section);
  };

  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <Text style={styles.title}>Focus Report</Text>
        <Text style={styles.subtitle}>{getTimeframeLabel()}</Text>
      </View>

      {/* Key Metrics Summary */}
      <View style={styles.summarySection}>
        <Text style={styles.sectionTitle}>Key Metrics</Text>
        <View style={styles.metricsGrid}>
          <View style={styles.metricCard}>
            <Ionicons name="calendar" size={20} color={colors.primary} />
            <Text style={styles.metricValue}>{analytics.sessionsCompleted}</Text>
            <Text style={styles.metricLabel}>Total Sessions</Text>
            <Text style={styles.metricChange}>
              {progressData.sessions.change > 0 ? '+' : ''}{Math.round(progressData.sessions.change)}%
            </Text>
          </View>
          
          <View style={styles.metricCard}>
            <Ionicons name="time" size={20} color={colors.accent} />
            <Text style={styles.metricValue}>
              {Math.round(analytics.totalFocusTime / 60000)}m
            </Text>
            <Text style={styles.metricLabel}>Focus Time</Text>
            <Text style={styles.metricChange}>
              {progressData.focusTime.change > 0 ? '+' : ''}{Math.round(progressData.focusTime.change)}%
            </Text>
          </View>
          
          <View style={styles.metricCard}>
            <Ionicons name="trending-up" size={20} color={colors.success} />
            <Text style={styles.metricValue}>
              {Math.round((analytics.sessionsCompleted / (analytics.sessionsCompleted + analytics.sessionsCancelled)) * 100)}%
            </Text>
            <Text style={styles.metricLabel}>Success Rate</Text>
            <Text style={styles.metricChange}>
              {progressData.successRate.change > 0 ? '+' : ''}{Math.round(progressData.successRate.change)}%
            </Text>
          </View>
          
          <View style={styles.metricCard}>
            <Ionicons name="flame" size={20} color={colors.warning} />
            <Text style={styles.metricValue}>{analytics.currentStreak}</Text>
            <Text style={styles.metricLabel}>Day Streak</Text>
            <Text style={styles.metricChange}>Current</Text>
          </View>
        </View>
      </View>

      {/* AI Insights */}
      {insights.length > 0 && (
        <View style={styles.insightsSection}>
          <Text style={styles.sectionTitle}>AI Insights</Text>
          {insights.map((insight, index) => (
            <View key={index} style={styles.insightCard}>
              <View style={styles.insightHeader}>
                <Ionicons name={insight.icon as any} size={20} color={getInsightColor(insight.type)} />
                <Text style={styles.insightTitle}>{insight.title}</Text>
              </View>
              <Text style={styles.insightDescription}>{insight.description}</Text>
            </View>
          ))}
        </View>
      )}

      {/* Detailed Breakdown */}
      <View style={styles.breakdownSection}>
        <Text style={styles.sectionTitle}>Detailed Breakdown</Text>
        
        <TouchableOpacity
          style={styles.breakdownItem}
          onPress={() => toggleSection('patterns')}
        >
          <View style={styles.breakdownHeader}>
            <Ionicons name="analytics" size={20} color={colors.primary} />
            <Text style={styles.breakdownTitle}>Focus Patterns</Text>
            <Ionicons 
              name={expandedSection === 'patterns' ? 'chevron-up' : 'chevron-down'} 
              size={16} 
              color={colors.textSecondary} 
            />
          </View>
          {expandedSection === 'patterns' && (
            <View style={styles.breakdownContent}>
              <Text style={styles.breakdownText}>
                Peak focus hours: {analytics.peakFocusHours.join(', ') || 'Not enough data'}
              </Text>
              <Text style={styles.breakdownText}>
                Most productive day: Tuesday (sample data)
              </Text>
              <Text style={styles.breakdownText}>
                Average session duration: {Math.round(analytics.averageSessionDuration / 60000)} minutes
              </Text>
            </View>
          )}
        </TouchableOpacity>

        <TouchableOpacity
          style={styles.breakdownItem}
          onPress={() => toggleSection('distractions')}
        >
          <View style={styles.breakdownHeader}>
            <Ionicons name="warning" size={20} color={colors.warning} />
            <Text style={styles.breakdownTitle}>Distraction Analysis</Text>
            <Ionicons 
              name={expandedSection === 'distractions' ? 'chevron-up' : 'chevron-down'} 
              size={16} 
              color={colors.textSecondary} 
            />
          </View>
          {expandedSection === 'distractions' && (
            <View style={styles.breakdownContent}>
              <Text style={styles.breakdownText}>
                Total distractions: {analytics.distractionCount}
              </Text>
              <Text style={styles.breakdownText}>
                Most common time: {analytics.distractionPatterns[0]?.hour || 15}:00 (sample)
              </Text>
              <Text style={styles.breakdownText}>
                Recommended action: Use Timer Lock Mode
              </Text>
            </View>
          )}
        </TouchableOpacity>
      </View>

      {/* Action Buttons */}
      <View style={styles.actionsContainer}>
        <TouchableOpacity style={styles.actionButton} onPress={exportReport}>
          <Ionicons name="share" size={20} color={colors.primary} />
          <Text style={styles.actionButtonText}>Share Report</Text>
        </TouchableOpacity>
        
        <TouchableOpacity style={styles.actionButton} onPress={() => onExport('csv')}>
          <Ionicons name="download" size={20} color={colors.primary} />
          <Text style={styles.actionButtonText}>Export CSV</Text>
        </TouchableOpacity>
        
        <TouchableOpacity style={styles.actionButton} onPress={() => onExport('json')}>
          <Ionicons name="document" size={20} color={colors.primary} />
          <Text style={styles.actionButtonText}>Export JSON</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
};

const getInsightColor = (type: string) => {
  switch (type) {
    case 'positive': return Colors.dark.success;
    case 'improvement': return Colors.dark.warning;
    case 'achievement': return Colors.dark.accent;
    default: return Colors.dark.primary;
  }
};

const styles = StyleSheet.create({
  container: {
    backgroundColor: colors.surface,
    margin: 16,
    padding: 16,
    borderRadius: 16,
    elevation: 3,
    shadowColor: colors.shadow,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
  },
  header: {
    marginBottom: 16,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    color: colors.text,
  },
  subtitle: {
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.text,
    marginBottom: 12,
  },
  summarySection: {
    marginBottom: 16,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  metricCard: {
    width: '48%',
    backgroundColor: colors.backgroundSecondary,
    padding: 12,
    borderRadius: 8,
    alignItems: 'center',
    marginBottom: 8,
  },
  metricValue: {
    fontSize: 20,
    fontWeight: 'bold',
    color: colors.text,
    marginVertical: 4,
  },
  metricLabel: {
    fontSize: 10,
    color: colors.textSecondary,
    textAlign: 'center',
  },
  metricChange: {
    fontSize: 10,
    fontWeight: '600',
    marginTop: 2,
  },
  insightsSection: {
    marginBottom: 16,
  },
  insightCard: {
    backgroundColor: colors.backgroundSecondary,
    padding: 12,
    borderRadius: 8,
    marginBottom: 8,
  },
  insightHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 4,
  },
  insightTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.text,
    marginLeft: 8,
  },
  insightDescription: {
    fontSize: 12,
    color: colors.textSecondary,
    lineHeight: 16,
  },
  breakdownSection: {
    marginBottom: 16,
  },
  breakdownItem: {
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 8,
    marginBottom: 8,
    overflow: 'hidden',
  },
  breakdownHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 12,
  },
  breakdownTitle: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.text,
    flex: 1,
    marginLeft: 8,
  },
  breakdownContent: {
    paddingHorizontal: 12,
    paddingBottom: 12,
  },
  breakdownText: {
    fontSize: 12,
    color: colors.textSecondary,
    marginBottom: 4,
  },
  actionsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingTop: 16,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    marginHorizontal: 4,
    backgroundColor: colors.backgroundSecondary,
    borderRadius: 6,
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.primary,
    marginLeft: 4,
  },
});

export default FocusReport;